- name: Install pyvmomi into the ansible (virtualenv)
  ansible.builtin.pip:
    name: pyvmomi
    virtualenv: "{{ home_path }}/bootstrap/ansible"

- name: Add Public VM Portgroup
  community.vmware.vmware_portgroup:
    hostname: "{{ item.0 }}"
    username: "{{ esx_username }}"
    password: "{{ item.1 | b64decode }}"
    switch: "{{ vswitch_name }}"
    portgroup: "{{ pub_portgroup_name }}"
    vlan_id: "{{ pub_vlan_id }}"
    hosts:
     - "{{ item.0 }}"
    validate_certs: false
  with_together:
        - "{{ groups['esx'] }}"
        - "{{ esx_passwords }}"

- name: Add Private VM Portgroup
  community.vmware.vmware_portgroup:
    hostname: "{{ item.0 }}"
    username: "{{ esx_username }}"
    password: "{{ item.1 | b64decode }}"
    switch: "{{ vswitch_name }}"
    portgroup: "{{ priv_portgroup_name }}"
    vlan_id: "{{ priv_vlan_id }}"
    hosts:
     - "{{ item.0 }}"
    validate_certs: false
  with_together:
        - "{{ groups['esx'] }}"
        - "{{ esx_passwords }}"

- name: Mount NFS v4.1 datastore
  community.vmware.vmware_host_datastore:
    hostname: "{{ item.0 }}"
    username: "{{ esx_username }}"
    password: "{{ item.1 | b64decode }}"
    datastore_name: "NFS"
    datastore_type: "nfs41"
    nfs_server:  "{{ priv_cidr | ansible.utils.nthhost('1') }}" 
    nfs_path: "/nfs/esx"
    nfs_ro: no
    state: present
    validate_certs: false
  with_together:
        - "{{ groups['esx'] }}"
        - "{{ esx_passwords }}"
